Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using Web_CrowdBook.Utils;
using ETC.BL.Utilities;
using System.IO;
using System.Drawing.Imaging;

namespace Web_CrowdBook.Controllers
{
    public class ImageController : Controller
    {
        #region Actions
        public ActionResult Group(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.GROUP_AVATAR, width, height);
        }
        public ActionResult GroupCover(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.GROUP_COVER, width, height);
        }
        public ActionResult Product(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.PRODUCT, width, height);
        }
        public ActionResult Person(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.PERSON, width, height);
        }
        public ActionResult PersonTemp(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.PERSON_TEMP, width, height);
        }

        public ActionResult GroupTemp(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.GROUP_AVATAR_TEMP, width, height);
        }
        public ActionResult GroupCoverTemp(long id, int width = 0, int height = 0)
        {
            return new ImageResult(id, ImageType.GROUP_COVER_TEMP, width, height);
        }
        #endregion
    }

    #region ImageType
    public enum ImageType
    {
        GROUP_AVATAR,
        GROUP_COVER,
        PRODUCT,
        PERSON,
        PERSON_TEMP,
        GROUP_AVATAR_TEMP,
        GROUP_COVER_TEMP
    }
    #endregion

    public class ImageResult : ViewResult
    {
        #region Constructor
        public ImageResult(long id, ImageType type, int width = 0, int height = 0)
        {
            Id = id;
            Type = type;
            if (width > 0 || height > 0)
            {
                Width = width;
                Height = height;
            }
        }
        #endregion

        public long Id { get; set; }
        public ImageType Type { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }

        public override void ExecuteResult(ControllerContext context)
        {
            Image img = null;
            string imageName = "";
            string imageType = "";
            string resourceExtension = "";
            string url = "";

            switch (Type)
            {
                case ImageType.GROUP_AVATAR:
                    GetImageGroup(context, ETC.BL.Common.FileType.AVATAR, ref img, ref imageName, ref imageType, ref url);
                    break;
                case ImageType.GROUP_COVER:
                    GetImageGroup(context, ETC.BL.Common.FileType.COVER, ref img, ref imageName, ref imageType, ref url);
                    break;
                case ImageType.PRODUCT:
                    GetImageProduct(context, ref img, ref imageName, ref imageType, ref url, ref resourceExtension);
                    break;
                case ImageType.PERSON:
                    GetAvatarPerson(ref img, ref imageName, ref imageType, ref url);
                    break;
                case ImageType.PERSON_TEMP:
                    GetAvatarPersonTemp(context, ref img, ref imageName, ref imageType, ref url);
                    break;

                case ImageType.GROUP_AVATAR_TEMP:
                    GetImageGroupTemp(context, ETC.BL.Common.FileType.AVATAR, ref img, ref imageName, ref imageType, ref url);
                    break;
                case ImageType.GROUP_COVER_TEMP:
                    GetImageGroupTemp(context, ETC.BL.Common.FileType.COVER, ref img, ref imageName, ref imageType, ref url);
                    break;
            }

            context.HttpContext.Response.Clear();
            context.HttpContext.Response.AddHeader("content-disposition", string.Format("filename={0}", "CrowdBook"));
            //context.HttpContext.Response.ContentType = imageType;

            if (img != null)
            {
                if (Width == 0 || Height == 0)
                    context.HttpContext.Response.BinaryWrite(FileHandler.ConvertImageToBytes(img));
                else
                    context.HttpContext.Response.BinaryWrite(ResizeImage(img, Width, Height));
            }
            else
            {
                switch (Type)
                {
                    case ImageType.GROUP_AVATAR:
                    case ImageType.GROUP_AVATAR_TEMP:
                        img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/group.png"));
                        break;
                    case ImageType.GROUP_COVER:
                        img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/cover.png"));
                        Width = 990;
                        break;
                    case ImageType.PRODUCT:
                        switch (resourceExtension)
	                    {
                            case ExtensionFilesType.PDF:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/pdf.jpg"));
                                break;
                            case ExtensionFilesType.EPUB:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/epub.jpg"));
                                break;
                            case ExtensionFilesType.WORD_2003:
                            case ExtensionFilesType.WORD:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/word.jpg"));
                                break;
                            case ExtensionFilesType.EXCEL_2003:
                            case ExtensionFilesType.EXCEL:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/excel.jpg"));
                                break;
                            case ExtensionFilesType.POWER_POINT:
                            case ExtensionFilesType.POWER_POINT_2003:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/power point.jpg"));
                                break;
                            case ExtensionFilesType.IMAGE_JPG_A:
                            case ExtensionFilesType.IMAGE_JPG_B:
                            case ExtensionFilesType.IMAGE_PNG:
                            case ExtensionFilesType.IMAGE_GIF:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/resource.jpg"));
                                break;
                            default:
                                img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/Covers/resource.jpg"));
                                break;
	                    }
                        break;
                    case ImageType.PERSON:
                    case ImageType.PERSON_TEMP:
                        img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/person.png"));
                        break;
                    default:
                        img = Image.FromFile(context.HttpContext.Server.MapPath("~/Images/default.png"));
                        break;
                }
                if (Width == 0 || Height == 0)
                    context.HttpContext.Response.BinaryWrite(FileHandler.ConvertImageToBytes(img));
                else
                    context.HttpContext.Response.BinaryWrite(ResizeImage(img, Width, Height));
            }
            context.HttpContext.Response.ContentType = "image/JPEG";
            //context.HttpContext.Response.ContentType = FileHandler.GetMimeType(img);
        }

        #region GetUrlBase
        string GetUrlBase(ControllerContext context)
        {
            string url = "";
            if (context.HttpContext.Cache["GroupImageUrlBase"] == null)
            {
                ETC.BL.ProductBL bl = new ETC.BL.ProductBL();
                ETC.Structures.Models.Products.UrlDouwnload urlDown = bl.GetUrlDownload();
                url = urlDown.urlD;
                context.HttpContext.Cache["GroupImageUrlBase"] = url;
            }
            else
                url = context.HttpContext.Cache["GroupImageUrlBase"].ToString();
            return url;
        }
        #endregion

        #region GetImage
        Image GetImage(string url)
        {
            Image img = null;
            try
            {
                System.Net.WebRequest req = System.Net.WebRequest.Create(url);
                using (System.Net.WebResponse response = req.GetResponse())
                {
                    using (System.IO.Stream stream = response.GetResponseStream())
                        img = System.Drawing.Image.FromStream(stream);
                }
            }
            catch (Exception)
            {
            }
            return img;
        }
        #endregion

        #region GetImageGroup
        void GetImageGroup(ControllerContext context, ETC.BL.Common.FileType fileType, ref Image img, ref string imageName, ref string imageType, ref string url)
        {
            ETC.BL.Groups.IGroupBL bl = new ETC.BL.Groups.GroupBL();
            ETC.Structures.Models.Groups.GroupFile groupFile = bl.GetGroupFile(Id, fileType);
            if (groupFile != null)
            {
                imageName = groupFile.Name;
                imageType = groupFile.MimeType;
            }
            if (!string.IsNullOrEmpty(imageName))
            {
                url = string.Format("{0}/{1}", GetUrlBase(context), imageName);
                img = GetImage(url);
            }
        }
        #endregion

Views/Shared/_Layout.cshtml
@model Web_CrowdBook.Models.BaseModel
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="/Images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/Images/favicon.ico" type="image/x-icon">
    <meta charset="utf-8" />
    <meta content="text/html; charset=iso-8859-1;" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width" />
    @RenderSection("metas", required: false)
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/global")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div id="wrap_pag"><div id="main_pag"><div id="wrap_header">
        <div id="header" class="size-dym">
            <a class="logo" href="@Url.Action("Index", "Home")" title="Crowdbook.com"><i class="ico-logo crowdbook_ijsg"></i></a>
            <div id="menu-nav">
                <ul><li><a href="@Url.Action("Index", "Home")"><span>Inicio</span></a></li></ul>
            </div>
            <div id="menu-user">
                <ul>
                    <li class="list-main"><div class="avatar round-img"><span class="round-img-inner"><a class="round-img-a" href="@Url.Action("Index", "Profile")"><img id="imgAvatarHeader" alt="@Model.Person.FirstName" src="@Url.Action("Person", "Image", new { id = (int)Model.Person.Id, width = 60, height = 60 })"></a></span></div></li>
                    <li class="list-main userinfo">
                        @if(!string.IsNullOrEmpty(Model.Person.InstitutionAlias)){
                            <strong class="name no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                            <div class="institution no-wrap-ellips">@Model.Person.InstitutionAlias</div>
                        }
                        else if(!string.IsNullOrEmpty(Model.Person.Institution)){
                            <strong class="name no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                            <div class="institution no-wrap-ellips">@Model.Person.Institution</div>
                        }
                        else{
                            <strong class="name not-institution no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                        }
                    </li>
                    <li id="menu-user-main">
                        <a class="a-dropdown"><i class="ico-drodown"></i></a>
                        <div class="menu-drop">
                            <ul class="navigation">
                                <li class="name"><strong class="no-wrap-ellips"><a href="@Url.Action("Index", "Profile")">@Model.Person.Fullname</a></strong></li>
                                <li><a id="btn-create-g" href="@Url.Action("Index", "Create")"><span>Crear grupo</span></a></li>
                                <li><a href="@Url.Action("Index", "MyGroups")"><span>Mis grupos</span></a></li>
                                <li><a href="@Url.Action("Index", "Profile")"><span>Editar perfil</span></a></li>
                                <li class="logout"><a href="@Url.Action("LogOut", "Account")"><span>Cerrar Sesión</span></a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
            <div id="menu-notification"><ul><li><i class="ico-bell"></i></li></ul></div>
            <div id="menu-search">
                @using (Html.BeginForm("SearchGroup", "MyGroups", FormMethod.Post, new { @class = "form-horizontal" })){
                    <div class="inner"><input id="txSearchHeader" type="search" name="search" placeholder="Buscar grupos" /><i class="ico-search"></i></div>
                }
            </div>
        </div></div>
    <div class="size-dym"><div id="content" class="clearfix">        
        <div id="page-content">
            <div id="col-left">
                <div class="clearfix">
                    <div class="avatar round-img"><span class="round-img-inner"><a class="round-img-a" href="@Url.Action("Index", "Profile")"><img id="imgAvatarSide" alt="@Model.Person.FirstName" src="@Url.Action("Person", "Image", new { id = (int)Model.Person.Id, width = 105, height = 105 })"></a></span></div>
                    <div class="user"><a href="@Url.Action("Index", "Profile")"><strong class="overflow-ellips">@Model.Person.FirstName @Model.Person.LastName</strong></a>
                        <h5>@Model.Person.Institution</h5>
                    </div>
                    <nav>
                        <ul class="navigation">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            @*<li>@Html.ActionLink("My Crowd", "Index", "Home")<i class="my-crowd bg-green">0</i></li>*@
                            <li>@Html.ActionLink("Mis Grupos", "Index", "MyGroups")<i class="my-groups bg-blue"><span id="mnSGroups">@Model.Person.MyGroups</span></i></li>
                            <li>@Html.ActionLink("Biblioteca", "Index", "Library")<i class="resources bg-orange"><span id="mnSRes">@Model.Person.Products</span></i></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div id="side-main">@RenderBody()</div>
        </div>
    </div></div></div></div>
    <div id="footer"><div class="inner">
        <div>© Crowdbook S.A.S - Crowdbook™ 2014&nbsp <ul class="policy"><li>@Html.ActionLink("Privacidad", "Policy", "Account", null, new { @target="_blank" })</li></ul></div>
        <div>Versión 0.2.0</div>
    </div></div>
    <div id="modal-loading" class="modal"><img alt="" src="~/Images/loading.gif" /></div>
</body>
</html>

Views/Shared/_LayoutWithLogin.cshtml
@model Web_CrowdBook.Models.BaseModel
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="/Images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/Images/favicon.ico" type="image/x-icon">
    <meta charset="utf-8" />
    <meta content="text/html; charset=iso-8859-1;" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width" />
    @RenderSection("metas", required: false)
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/global")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div id="wrap_pag"><div id="main_pag"><div id="wrap_header">
        <div id="header" class="size-dym">
            <a class="logo" href="@Url.Action("Index", "Home")" title="CrowdBook.com"><i class="ico-logo crowdbook_ijsg"></i></a>
            <div id="menu-nav">
                <ul><li><a href="@Url.Action("Index", "Home")"><span>Inicio</span></a></li></ul>
            </div>
            <div id="menu-user">
                <ul>
                    @if (Request.IsAuthenticated){
                    <li class="list-main"><div class="avatar round-img"><span class="round-img-inner"><a class="round-img-a" href="@Url.Action("Index", "Profile")"><img id="imgAvatarHeader" alt="@Model.Person.FirstName" src="@Url.Action("Person", "Image", new { id = (int)Model.Person.Id, width = 60, height = 60 })"></a></span></div></li>
                    <li class="list-main userinfo">
                        @if(!string.IsNullOrEmpty(Model.Person.InstitutionAlias)){
                            <strong class="name no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                            <div class="institution no-wrap-ellips">@Model.Person.InstitutionAlias</div>
                        }
                        else if(!string.IsNullOrEmpty(Model.Person.Institution)){
                            <strong class="name no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                            <div class="institution no-wrap-ellips">@Model.Person.Institution</div>
                        }
                        else{
                            <strong class="name not-institution no-wrap-ellips"><a href="@Url.Action("Index", "Home")">@Model.Person.FirstName</a></strong>
                        }
                    </li>
                    <li id="menu-user-main">
                        <a class="a-dropdown"><i class="ico-drodown"></i></a>
                        <div class="menu-drop">
                            <ul class="navigation">
                                <li class="name"><strong class="no-wrap-ellips"><a href="@Url.Action("Index", "Profile")">@Model.Person.Fullname</a></strong></li>
                                <li><a id="btn-create-g" href="@Url.Action("Index", "Create")"><span>Crear grupo</span></a></li>
                                <li><a href="@Url.Action("Index", "MyGroups")"><span>Mis grupos</span></a></li>
                                <li><a href="@Url.Action("Index", "Profile")"><span>Editar perfil</span></a></li>
                                <li class="logout"><a href="@Url.Action("LogOut", "Account")"><span>Cerrar Sesión</span></a></li>
                            </ul>
                        </div>
                    </li>
                    }
                    else{
                        <li class="list-main"><div class="avatar round-img"><span class="round-img-inner"><a href="@Url.Action("Index", "Account")"><img alt="Login" src="~/Images/person.png"></a></span></div></li>
                        <li class="list-main userinfo">
                            <strong class="name"><a href="@Url.Action("Index", "Account")">Login</a></strong>
                            <div class="institution"><a href="@Url.Action("Index", "Account")">Registrarse</a></div>
                        </li>
                    }
                </ul>
            </div>
            <div id="menu-notification"><ul><li><i class="ico-bell"></i></li></ul></div>
            <div id="menu-search">
                @using (Html.BeginForm("SearchGroup", "MyGroups", FormMethod.Post, new { @class = "form-horizontal" })){
                    <div class="inner"><input id="txSearchHeader" type="search" name="search" placeholder="Buscar grupos" /><i class="ico-search"></i></div>
                }
            </div>
        </div></div>
    <div class="size-dym"><div id="content" class="clearfix">        
        <div id="page-content">
            @if (Request.IsAuthenticated){
            <div id="col-left">
                <div class="clearfix">
                    <div class="avatar round-img"><span class="round-img-inner"><a class="round-img-a" href="@Url.Action("Index", "Profile")"><img id="imgAvatarSide" alt="@Model.Person.FirstName" src="@Url.Action("Person", "Image", new { id = (int)Model.Person.Id, width = 105, height = 105 })"></a></span></div>
                    <div class="user">
                        <strong>@Model.Person.FirstName @Model.Person.LastName</strong>
                        <h5>@Model.Person.Institution</h5>
                    </div>
                    <nav>
                        <ul class="navigation">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            @*<li>@Html.ActionLink("My Crowd", "Index", "Home")<i class="my-crowd bg-green">0</i></li>*@
                            <li>@Html.ActionLink("Mis Grupos", "Index", "MyGroups")<i class="my-groups bg-blue">@Model.Person.MyGroups</i></li>
                            <li>@Html.ActionLink("Biblioteca", "Index", "Library")<i class="resources bg-orange"><span id="mnSRes">@Model.Person.Products</span></i></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div id="side-main">@RenderBody()</div>
            }
            else{
            <div id="side-main" style="margin-left:0;">@RenderBody()</div>
            }
        </div>
    </div></div></div></div>
    <div id="footer"><div class="inner">
        <div>© Crowdbook S.A.S - Crowdbook™ 2014&nbsp <ul class="policy"><li>@Html.ActionLink("Privacidad", "Policy", "Account", null, new { @target="_blank" })</li></ul></div>
        <div>Versión 0.2.0</div>
    </div></div>
</body>
</html>